# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.CharField(default='/static/public/pics/user.jpg', max_length=128),
        ),
    ]
