# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20180411_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pic',
            field=models.CharField(default='/static/public/pics/user.png', max_length=128),
        ),
    ]
