# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20180412_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='delete_data',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
