# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0008_auto_20180413_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('total_number', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Order')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('addname', models.CharField(max_length=32)),
                ('addphone', models.CharField(max_length=11)),
                ('addcode', models.IntegerField()),
                ('usersid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='addressid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UsersAddress'),
        ),
    ]
