# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180422_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addtime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
