# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
