# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180423_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='price',
        ),
    ]
